### ISSUE TITLE
Windows wheel missing dependencies

### ISSUE THREAD

**Issue by daniel-edwards-iress** [ssciwr/clang-format-wheel#22]
Version 13.0.0 is missing dependencies that prevent clang-format from running on windows.

![image](https://user-images.githubusercontent.com/48459638/142513289-19ff400d-a889-43ad-a306-688146882860.png)
![image](https://user-images.githubusercontent.com/48459638/142513294-5add8fc0-df71-4db9-b62d-37e9299191dc.png)
![image](https://user-images.githubusercontent.com/48459638/142513308-8150fc24-ee5e-4061-a07f-698084b7c8f5.png)

**Comment by dokempf** [comment]
Thanks for reporting. Could you give a bit more context? Is this with the 32 or 64 Bit variant? What version of Python and Windows? How did you install/use `clang-format`? etc.

**Comment by nightlark** [comment]
It looks like this is because using the ninja generator on Windows just really likes picking up the gcc compiler included on the GitHub Actions chocolatey install, leading to dependencies on a variety of MinGW related DLLs.

Other than bundling MinGW DLLs in the Windows wheels, other options are:
- static link system libraries on Windows
- make the Windows builds use MSVC (either coercing Ninja to use the MSVC compiler which is a bit obnoxious, or use the default CMake generator on Windows instead of Ninja)

**Comment by daniel-edwards-iress** [comment]
> Thanks for reporting. Could you give a bit more context? Is this with the 32 or 64 Bit variant? What version of Python and Windows? How did you install/use `clang-format`? etc.

I'm running the 64bit version of clang-format installed using `pip install clang-format`. (Originally installed as part of pre-commit.)
Python version 3.10.1
Windows Version 21H1 (19043.1415)

**Comment by dchengTSC** [comment]
I am running into this issue on Windows as well. Steps to reproduce the issue:
In cmd.exe:
1. `pip install clang-format`
2. `clang-format`

Python version 3.9.6
Windows Version 10.0.19043

More context: I am trying to roll out precommit hooks to my Windows-based teammates using [pre-commit](https://pre-commit.com/). Most of them do not have the MinGW dlls anywhere on their system path.

**Comment by dokempf** [comment]
I think my favorite solution from @nightlark's analysis would be to just not use `Ninja` on Windows if this solves the issue. I will try that.
