### ISSUE TITLE
Missing aarch64 wheel for Linux

### ISSUE THREAD

**Issue by rexut** [ssciwr/clang-format-wheel#64]
First of all, thank you for all your efforts for packaging LLVM's clang-format and upload to PyPi. Recently, this package is used as "extra" package by Zephyr project and can also be installed very easily on Linux, macOS and Windows through the provided wheels without waiting for the rebuild as long as it is an x86 system.

Now, unfortunately, the ARM 64 bit architecture is not (yet) packaged as a wheel. So on a Raspberry Pi 4 this means an extremely long installation time, because a native C++ compile has to build the wheel from the sdist package first. This could be saved if there would be an aarch64 wheel already on PyPi.

I have seen in the GitHub worker that exactly this architecture is skipped. Is there a technical reason for this? What is required to ship manylinux-aarch64 as a wheel as well?

**Comment by dokempf** [comment]
I just published v16.0.0 and it includes a manylinux aarch64 Wheel. The problem with the emulated builds has always been hitting the six hour limit of GitHub Actions. For v16, it worked because the internal dependency structure of clang-format has changed (yet again) and now takes significantly less time to build.

**Comment by dokempf** [comment]
I am closing this for now as it does not apply to the latest major release.
